apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    appgw.ingress.kubernetes.io/use-private-ip: "false" 
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: "$NAMESPACE.k8s.freshworks.club"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
