name: PR checks
on:
  push:
    branches: ['milestone-1']
    # Typically for tag-based deployment you would have one tag per environment, e.g. dev/test/prod
  workflow_dispatch:

env:
  # Please change this to the name of your kubernetes namespace
  NAMESPACE: ${{ secrets.NAMESPACE }}

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: azure/k8s-set-context@v2
        name: Set-up kubernetes connection
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Apply k8s config
        run: make apply
